Muneeb/get floating license mode
cryptlex/lexfloatclient-python pull request #11
Opened 2024-07-16 08:47 UTC by muneebkq

add get floating license mode function

2024-08-01 17:39 UTC, ahmad-kemsan commented on cryptlex/lexfloatclient/lexfloatclient.py
>          Raises:
@muneebkq Why was this changed?

2024-08-01 17:42 UTC, ahmad-kemsan requested changes
Please check the comment

2024-08-02 08:55 UTC, muneebkq commented on cryptlex/lexfloatclient/lexfloatclient.py
>          Raises:
refactored

2024-08-06 11:51 UTC, ahmad-kemsan approved these changes

2024-08-06 11:52 UTC, merged