feat: add permission flag
cryptlex/lexfloatclient-python pull request #12
Opened 2024-07-16 08:50 UTC by muneebkq

2024-08-01 17:51 UTC, ahmad-kemsan commented on cryptlex/lexfloatclient/lexfloatclient.py
> +
@muneebkq Sets the permission flag.

2024-08-01 17:53 UTC, ahmad-kemsan requested changes
Please update the docs

2024-08-02 07:24 UTC, muneebkq commented on cryptlex/lexfloatclient/lexfloatclient.py
> +
changed to flag

2024-08-06 11:35 UTC, ahmad-kemsan approved these changes

2024-08-06 11:35 UTC, merged