feat: request-float-license
cryptlex/lexfloatclient-python pull request #14
Opened 2024-07-16 08:56 UTC by muneebkq

2024-08-01 17:31 UTC, ahmad-kemsan commented on cryptlex/lexfloatclient/lexfloatstatus_codes.py
@muneebkq Why these changes?

2024-08-01 19:11 UTC, ahmad-kemsan requested changes
Please check the comments

2024-08-02 07:25 UTC, muneebkq commented on cryptlex/lexfloatclient/lexfloatstatus_codes.py
This format is followed in every other function.

2024-08-06 09:29 UTC, ahmad-kemsan commented on cryptlex/lexfloatclient/lexfloatstatus_codes.py
> +
@muneebkq There are still many formatting issues that need to be resolved.

2024-08-06 09:29 UTC, ahmad-kemsan requested changes
Please check the comment

2024-08-06 11:44 UTC, ahmad-kemsan approved these changes

2024-08-06 11:51 UTC, merged